LAND_CARRY_CAPACITY = 8
WATER_CARRY_CAPACITY = 20
DEFAULT_MOVE_DISTANCE = 5.0
MOVE_CARRY_OVER = 0.0
BASE_TERRAIN_COST = 2.0
DIFFICULT_TERRAIN_COST = 4.0
MIN_TERRAIN_COST = 2.0
POP_FOOD_CONSUMPTION = 1